### ISSUE TITLE
Replace testcontainers with "something else"?

### ISSUE THREAD

**Issue by erikgb** [statnett/k3a-lag-exporter#62]
I think the testcontainers tests are slow, and we will also be affected by the DockerHub rate limits. There are some suggestions in https://github.com/testcontainers/testcontainers-java/issues/3099, but I personally think we could/should test this without containers. What about an in-memory embedded broker?

**Comment by sverrehu** [comment]
I have [the code](https://github.com/sverrehu/k3a-embedded) ready now, just need to figure out how to release a jar file. But that must be another day.

**Comment by sverrehu** [comment]
Those I found were either not updated for years, or delegated the embedding to testcontainers.

At least I had fun creating my little project, which I think is the absolute minimum required to embed a Java server.
